name: Terraform Check

on:
  pull_request:
    branches:
    - master

jobs:
  fmt:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run "terraform fmt"
      uses: hashicorp/terraform-github-actions/fmt@v0.3.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: terraform init
      uses: hashicorp/terraform-github-actions/init@v0.3.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: terraform validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
